version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_ENV=${REACT_APP_ENV}
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_ENV=${REACT_APP_ENV}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 