[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirects to handle client-side routing (for SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 